[package]
name = "actix_hello_world"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "actix_hello_world"
path = "src/main.rs"

[dev-dependencies]
reqwest = "0.11.23"

[dependencies]
actix-web = "4.4.1"
config = "0.13.4"
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }

[dependencies.sqlx]
default-features = false
features = ["runtime-tokio", "macros", "postgres", "uuid", "chrono", "migrate"]
